### ISSUE TITLE
Add drop empty column option

### ISSUE THREAD

**Issue by ecommandeur** [ecommandeur/python-xlsx-conv#3]
Sometimes there will be a lot of empty columns, e.g. at the end of worksheet. It would be nice if there was an option to drop all empty columns. That would make for a smaller dump with only columns that actually contain data.

**Comment by OmeshDebipersad** [comment]
Currently looking into this

**Comment by OmeshDebipersad** [comment]
Ik heb hier echt mn best voor gedaan, maar de enige manier (die ik zie) is om dit via pandas te doen, nadat de csv is weggeschreven, met lege kolommen. Het probleem is dat de data regel voor regel wordt toegevoegd aan een csv. We kunnen dus nooit checken gedurende de verwerking of alle kolommen leeg zijn. Zelfs na heel veel googlen blijft voor mij alleen pandas.read_csv en dan empty columns droppen over. Ik heb hier redelijk wat tijd in gestopt en het is zonde om facturabel door te blijven prutsen. Kijk maar of het acceptabel is en anders kan je het verwijderen.

**Comment by OmeshDebipersad** [comment]
Pandas werkt toch niet blijkt na het bouwen. Hij klaagt over iets van C.

**Comment by ecommandeur** [comment]
Easier option is to just limit the number of columns we output. E.g. if the limit is set to 1000 then we never output more than 1000 columns. That way we do not need to check if the columns are empty.

**Comment by ecommandeur** [comment]
See #6
