### ISSUE TITLE
Add option to read paths to Excels from file

### ISSUE THREAD

**Issue by ecommandeur** [ecommandeur/python-xlsx-conv#4]
At present the script takes the path to the input from an argument on the commandline. If the path to the file contains non ascii characters then it is tricky to pass the path via the commandline. It would be nice it the script can take one or more inputs from a file.

At present input is a required parameter that takes a path to an Excel file (.xlsx). Input should look at the extension and accept either an .xlsx or a .txt input. If the input is a .txt file then that should be a path to a text file which lists the inputs.

The .txt file should:
* be tab delimited 
* be encoded in utf-8 
* have a header "Input" 
* have one or more paths to .xlsx files (a path per line)

**Comment by ecommandeur** [comment]
Input should accept xlsx as well as xlsm files

**Comment by ecommandeur** [comment]
In theory input could also accept a directory and convert all xlsx files in that directory.

**Comment by ecommandeur** [comment]
Instead of

```
xlsx-conv -i D:\Temp\myexcel1.xlsx -o D:\output1
xlsx-conv -i D:\Temp\myexcel2.xlsx -o D:\output2
```

we want to be able to do 

```
xlsx-conv -i D:\Temp\inputs.txt
```
Where the input file looks like this

```
Input	OutputDir
D:\Temp\myexcel1.xlsx	D:\output1
D:\Temp\myexcel2.xlsx	D:\output2
```

**Comment by OmeshDebipersad** [comment]
I have fixed that the script will work with an input file. It makes an array containing inputfile and outputdir and just loops for each of them over your code. I saw that a lot of empty rows are being outputted to the csv's. I will look into that.

**Comment by OmeshDebipersad** [comment]
Implemented a loop over an inputfile containing the above structure. I append each row to an array as a tuple and then loop over this array to process each excel file.

I also implemented that there won't be unnecessary empty rows. I check if all values in the values are none (skip the first value if rowIndex=true) and if all values are none I break the loop.

**Comment by ecommandeur** [comment]
Rewritten script so it iterates over a list of dictionaries that is either filled based on commandline arguments alone or filled based on a txt file containing paths to the Excel files.

**Comment by ecommandeur** [comment]
Fixed
